name = "liff"
compatibility_date = "2024-07-25"
pages_build_output_dir = "./build/client"


# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
[placement]
mode = "smart"

[[r2_buckets]]
binding = "AUTOMIX_BUCKET"
bucket_name = "automix"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Docs:
# - https://developers.cloudflare.com/pages/functions/bindings/#environment-variables
# Note: Use secrets to store sensitive data.
# - https://developers.cloudflare.com/pages/functions/bindings/#secrets

[vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"
VITE_BASE_URL = "https://liff-dev.aiya.me"

######## PREVIEW environment config ########

[env.preview.vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"
VITE_BASE_URL = "https://liff-review.aiya.me"

######## PRODUCTION environment config ########

[env.production.vars]
DIRECTUS_URL = "https://console.portal.aiya.ai"
VITE_BASE_URL = "https://liff-dev.aiya.me"
